<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ME_ON_TRACK_LINK</name>
   <tag></tag>
   <elementGuidId>d79e0809-0c41-4a95-93e9-42815369ba79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ancestor::app-dashboard//*[text()='on-track'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[text()='response']/following-sibling::button//*[text()='comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text font-weight-light small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>on-track</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/main[@class=&quot;ng-tns-c0-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-app-root[@class=&quot;ng-tns-c2-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/main[@class=&quot;ng-tns-c2-1 ng-trigger ng-trigger-fadeAnimation&quot;]/app-strategy[@class=&quot;ng-tns-c26-3 ng-star-inserted&quot;]/main[@class=&quot;ng-tns-c26-3 ng-trigger ng-trigger-fadeAnimation ng-star-inserted&quot;]/app-strategy-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row board-wrapper justify-content-md-end&quot;]/div[@class=&quot;col-md-7 col-lg-9 col-xl-9 pl-2 pr-0 bg-primary-bg&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;bg-white my-2 p-1&quot;]/div[@class=&quot;d-flex row m-0 bg-white hvh-50 pl-1 pr-2 pb-1 pt-0&quot;]/app-dashboard-tiles[@class=&quot;row col-xl-4 col-lg-4 col-md-12 col-sm-12 mx-0 px-0 mt-0 pr-1 text-center text-white ng-star-inserted&quot;]/div[@class=&quot;dashboard-tiles col-sm-12 col-md-3 col-lg-6 col-xl-6 p-1 ng-star-inserted&quot;]/a[@class=&quot;text-white&quot;]/div[@class=&quot;w-100 h-100 bg-success-light&quot;]/div[@class=&quot;center-xy&quot;]/div[@class=&quot;text font-weight-light small&quot;]</value>
   </webElementProperties>
</WebElementEntity>
