<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ALL_LINK</name>
   <tag></tag>
   <elementGuidId>c1eb1299-8258-4929-8ad3-10e7b161d6ce</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link py-0 px-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>all</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarTogglerDemo02&quot;)/form[@class=&quot;form-inline ng-untouched ng-pristine ng-valid&quot;]/app-time-filter[1]/div[@class=&quot;ng-star-inserted&quot;]/ul[@class=&quot;time-filter navbar-nav small font-weight-light ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link py-0 px-1&quot;]</value>
   </webElementProperties>
</WebElementEntity>
