<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CREATED_BUTTON</name>
   <tag></tag>
   <elementGuidId>e0321a7e-db5f-49b2-83ed-ad4bf5e0f28f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/main[@class=&quot;ng-tns-c0-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-app-root[@class=&quot;ng-tns-c2-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/main[@class=&quot;ng-tns-c2-1 ng-trigger ng-trigger-fadeAnimation&quot;]/app-ideation[@class=&quot;ng-tns-c26-20 ng-star-inserted&quot;]/main[@class=&quot;ng-tns-c26-20 ng-trigger ng-trigger-fadeAnimation&quot;]/app-ideation-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid h-100&quot;]/div[@class=&quot;row board-wrapper justify-content-md-end justify-content-lg-between&quot;]/div[@class=&quot;col-md-7 col-lg-9 col-xl-9 scroll-y pl-md-2 pr-md-0 pt-lg-2 px-lg-2  position-relative mt-md-2 mt-lg-0 hvh-100&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row row-charts align-content-stretch&quot;]/div[@class=&quot;col-md-8 col-lg-6 px-md-0 py-md-2 py-lg-0 px-lg-2&quot;]/div[@class=&quot;d-flex bg-white h-100&quot;]/app-ideation-line-graph[@class=&quot;w-100 mx-2 ng-star-inserted&quot;]/div[@class=&quot;container-fluid h-100&quot;]/div[@class=&quot;row flex-row h-100 p-2&quot;]/div[@class=&quot;action-group align-self-start pb-2&quot;]/div[@class=&quot;d-flex graph-legend text-center&quot;]/div[@class=&quot;justify-content-between w-100&quot;]/div[@class=&quot;float-left&quot;]/span[@class=&quot;btn px-1 py-0 float-left&quot;]/button[@class=&quot;btn btn-outline-primary-light p-1 rounded-0 btn-sm btn-round active&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary-light p-1 rounded-0 btn-sm btn-round active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/main[@class=&quot;ng-tns-c0-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-app-root[@class=&quot;ng-tns-c2-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/main[@class=&quot;ng-tns-c2-1 ng-trigger ng-trigger-fadeAnimation&quot;]/app-ideation[@class=&quot;ng-tns-c26-20 ng-star-inserted&quot;]/main[@class=&quot;ng-tns-c26-20 ng-trigger ng-trigger-fadeAnimation&quot;]/app-ideation-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid h-100&quot;]/div[@class=&quot;row board-wrapper justify-content-md-end justify-content-lg-between&quot;]/div[@class=&quot;col-md-7 col-lg-9 col-xl-9 scroll-y pl-md-2 pr-md-0 pt-lg-2 px-lg-2  position-relative mt-md-2 mt-lg-0 hvh-100&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row row-charts align-content-stretch&quot;]/div[@class=&quot;col-md-8 col-lg-6 px-md-0 py-md-2 py-lg-0 px-lg-2&quot;]/div[@class=&quot;d-flex bg-white h-100&quot;]/app-ideation-line-graph[@class=&quot;w-100 mx-2 ng-star-inserted&quot;]/div[@class=&quot;container-fluid h-100&quot;]/div[@class=&quot;row flex-row h-100 p-2&quot;]/div[@class=&quot;action-group align-self-start pb-2&quot;]/div[@class=&quot;d-flex graph-legend text-center&quot;]/div[@class=&quot;justify-content-between w-100&quot;]/div[@class=&quot;float-left&quot;]/span[@class=&quot;btn px-1 py-0 float-left&quot;]/button[@class=&quot;btn btn-outline-primary-light p-1 rounded-0 btn-sm btn-round active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
