<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ME_ACHIEVED_BUTTON</name>
   <tag></tag>
   <elementGuidId>a039c4fd-7b3d-45fd-af1b-78d856150e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button/following-sibling::span[contains(text(),'achieved')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>achieved
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/main[@class=&quot;ng-tns-c0-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-app-root[@class=&quot;ng-tns-c2-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/main[@class=&quot;ng-tns-c2-1 ng-trigger ng-trigger-fadeAnimation&quot;]/app-strategy[@class=&quot;ng-tns-c26-3 ng-star-inserted&quot;]/main[@class=&quot;ng-tns-c26-3 ng-trigger ng-trigger-fadeAnimation ng-star-inserted&quot;]/app-strategy-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row board-wrapper justify-content-md-end&quot;]/div[@class=&quot;col-md-7 col-lg-9 col-xl-9 pl-2 pr-0 bg-primary-bg&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;bg-white my-2 p-1&quot;]/div[@class=&quot;d-flex row m-0 bg-white hvh-50 pl-1 pr-2 pb-1 pt-0&quot;]/app-dashboard-chart[@class=&quot;row col-xl-8 col-lg-8 col-md-12 col-sm-12 m-0 p-0 pt-1 text-center ng-star-inserted&quot;]/div[@class=&quot;d-chart d-flex flex-column border mb-1&quot;]/div[@class=&quot;action-group&quot;]/div[@class=&quot;d-flex graph-legend text-center justify-content-between border-bottom pb-1&quot;]/span[@class=&quot;btn mx-auto px-md-1&quot;]/span[@class=&quot;small&quot;]</value>
   </webElementProperties>
</WebElementEntity>
