<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request_Approval</name>
   <tag></tag>
   <elementGuidId>3ffe9c99-db03-485d-ba7b-c6d858f8229a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='response']/following-sibling::button//*[text()='comment']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and (text() = 'approval' or . = 'approval')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item small pl-1 ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>approval</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;ng-tns-c0-0&quot;]/main[@class=&quot;ng-tns-c0-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-app-root[@class=&quot;ng-tns-c2-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/div[@class=&quot;ng-tns-c2-1&quot;]/main[@class=&quot;ng-tns-c2-1 ng-trigger ng-trigger-fadeAnimation&quot;]/app-strategy[@class=&quot;ng-tns-c52-5 ng-star-inserted&quot;]/main[@class=&quot;ng-tns-c52-5 ng-trigger ng-trigger-fadeAnimation ng-star-inserted&quot;]/app-strategy-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row board-wrapper justify-content-md-end&quot;]/div[@class=&quot;social-section col-md-4 col-lg-3 col-xl-3 d-none d-sm-block bg-primary-bg&quot;]/app-social-section[1]/div[@class=&quot;wrapper position-relative&quot;]/div[@class=&quot;post-wrapper bg-gray-200 shadow-bottom d-flex w-100 p-1&quot;]/div[@class=&quot;input-wrapper bg-transparent ml-0 px-1&quot;]/app-social-card-post[1]/div[@class=&quot;w-100 float-left pl-0 pr-0 py-2&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;input-group-prepend input-group-sm border-0 position-relative w-100 mb-2&quot;]/div[@class=&quot;btn-group dropdown&quot;]/div[@class=&quot;row justify-content-between dropdown-menu rounded-0 border-0 small py-0 ng-star-inserted&quot;]/div[@class=&quot;col-6 float-left py-1 px-0&quot;]/button[@class=&quot;dropdown-item small pl-1 ng-star-inserted&quot;]</value>
   </webElementProperties>
</WebElementEntity>
